name: "Lint (server)"

on:
    # Run on every push to a branch other than main that changes server/
    push:
        branches-ignore: [main]
        paths:
            - "server/**"
            - ".github/workflows/server-lint.yml"

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: server
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup go
              uses: actions/setup-go@v5
              with:
                  go-version-file: "server/go.mod"
                  cache: true

            - name: Install dependencies
              run: sudo apt-get update && sudo apt-get install libsodium-dev

            - name: Lint
              run: "./scripts/lint.sh"
