name: "Sync Crowdin translations (web)"

on:
    push:
        paths:
            # Run workflow when web's en-US/translation.json is changed
            - "web/apps/photos/public/locales/en-US/translation.json"
            # Or the workflow itself is changed
            - ".github/workflows/web-crowdin.yml"
        branches: [main]
    schedule:
        # See: [Note: Run every 24 hours]
        - cron: "20 1 * * *"
    # Also allow manually running the workflow
    workflow_dispatch:

jobs:
    synchronize-with-crowdin:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Crowdin's action
              uses: crowdin/github-action@v1
              with:
                  base_path: "web/"
                  config: "web/crowdin.yml"
                  upload_sources: true
                  upload_translations: true
                  download_translations: true
                  localization_branch_name: crowdin-translations-web
                  create_pull_request: true
                  skip_untranslated_strings: true
                  pull_request_title: "[web] New translations"
                  pull_request_body: "New translations from [Crowdin](https://crowdin.com/project/ente-photos-web)"
                  pull_request_base_branch_name: "main"
                  project_id: 569613
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
